### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by shogo11** [shogo11/chat-space#10]
#IPアドレス
54.95.110.100

**Comment by keisukekodama** [comment]
提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！


**○ 2回目以降の自動更新の挙動が確認できない**
1回目のメッセージを送信後の自動更新の挙動は確認できましたが、2回目以降は自動更新の挙動が確認できませんでした。
何度、メッセージを送信しても自動更新が行われるようにしましょう。

参考カリキュラム：https://master.tech-camp.in/curriculums/4278

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shogo11** [comment]
修正しました。

**Comment by naru6117** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂いたところ、前回の修正事項は修正が確認できました！
新たに以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
①グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう
②送信したメッセージにカリキュラム指定の通り、表示されるようにしましょう

### [修正箇所の現在の画像]
①
<img width="1431" alt="自動更新" src="https://user-images.githubusercontent.com/49669977/86211637-afb98d00-bbb1-11ea-893f-d7bb77785510.png">

②
![スクリーンショット 2020-07-01 15 40 09](https://user-images.githubusercontent.com/49669977/86211654-b516d780-bbb1-11ea-9e69-81a09ec68552.png)


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shogo11** [comment]
修正しました。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、①については修正が確認できました！
ありがとうございます(^^)
②は引き続き不備が見受けられましたので修正をお願いします！

### [修正箇所]
**・送信したメッセージにカリキュラム指定の通り、表示されるようにしましょう**

### [見本画像（カリキュラム内の画像）]
<img width="466" alt="スクリーンショット 2020-06-30 12 11 46" src="https://user-images.githubusercontent.com/49669977/86226491-b69eca80-bbc6-11ea-8e06-23156f8d6f39.png">


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by shogo11** [comment]
修正しました。

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
